# Generated by Django 4.1.3 on 2023-01-19 17:12

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_alter_post_liked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='liked',
            field=models.ManyToManyField(blank=True, default=False, null=True, related_name='liked', to=settings.AUTH_USER_MODEL),
        ),
    ]
