# Generated by Django 4.1.3 on 2023-01-19 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
    ]
