# Generated by Django 4.1.3 on 2023-01-19 22:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0019_post_liked'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='liked',
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likedBy', to=settings.AUTH_USER_MODEL)),
                ('postedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postedBy', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
