# Generated by Django 4.1.3 on 2023-01-19 22:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0020_remove_post_liked_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
