# Generated by Django 4.1.3 on 2023-01-19 23:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0021_remove_post_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='postedBy',
        ),
        migrations.AddField(
            model_name='likes',
            name='post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='network.post'),
            preserve_default=False,
        ),
    ]
