# Generated by Django 4.1.3 on 2023-02-04 17:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0024_user_profilepiture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='profilePiture',
            new_name='profilePicture',
        ),
    ]
