# Generated by Django 4.1.3 on 2023-02-04 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0025_rename_profilepiture_user_profilepicture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default-profile-pic.png', upload_to='profile_pics/'),
        ),
    ]
