# Generated by Django 4.1.3 on 2023-02-04 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0026_alter_user_profilepicture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profilePicture',
        ),
    ]
