# Generated by Django 4.1.3 on 2023-02-04 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0027_remove_user_profilepicture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profilePicture',
            field=models.ImageField(blank=True, default='default-profile-pic.png', upload_to='profile_pics/'),
        ),
    ]
